export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_UPDATE_INFORMATION_REQUEST = 'USER_UPDATE_INFORMATION_REQUEST';
export const USER_UPDATE_DELIVERY_ADDRESS_REQUEST = 'USER_UPDATE_DELIVERY_ADDRESS_REQUEST';
export const FETCH_DELIVERY_ADDRESS_REQUEST = 'FETCH_DELIVERY_ADDRESS_REQUEST';
export const FETCH_ORDER_PRODUCT = 'FETCH_ORDER_PRODUCT';
export const ADD_ORDER = 'ADD_ORDER';
